name: Labeler
on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]
permissions:
  contents: read # to determine modified files (actions/labeler)

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
